# create_clock -period 10.000 -name clk_gl -waveform {0.000 5.000} [get_ports clk_gl]

set_property PACKAGE_PIN E3 [get_ports clk_gl]
set_property PACKAGE_PIN N17 [get_ports rst]

set_property PACKAGE_PIN T10 [get_ports {o_seg[0]}]
set_property PACKAGE_PIN R10 [get_ports {o_seg[1]}]
set_property PACKAGE_PIN K16 [get_ports {o_seg[2]}]
set_property PACKAGE_PIN K13 [get_ports {o_seg[3]}]
set_property PACKAGE_PIN P15 [get_ports {o_seg[4]}]
set_property PACKAGE_PIN T11 [get_ports {o_seg[5]}]
set_property PACKAGE_PIN L18 [get_ports {o_seg[6]}]
set_property PACKAGE_PIN H15 [get_ports {o_seg[7]}]

set_property PACKAGE_PIN J17 [get_ports {o_sel[0]}]
set_property PACKAGE_PIN J18 [get_ports {o_sel[1]}]
set_property PACKAGE_PIN T9 [get_ports {o_sel[2]}]
set_property PACKAGE_PIN J14 [get_ports {o_sel[3]}]
set_property PACKAGE_PIN P14 [get_ports {o_sel[4]}]
set_property PACKAGE_PIN T14 [get_ports {o_sel[5]}]
set_property PACKAGE_PIN K2 [get_ports {o_sel[6]}]
set_property PACKAGE_PIN U13 [get_ports {o_sel[7]}]

set_property PACKAGE_PIN V11 [get_ports {o_test_result[15]}]
set_property PACKAGE_PIN V12 [get_ports {o_test_result[14]}]
set_property PACKAGE_PIN V14 [get_ports {o_test_result[13]}]
set_property PACKAGE_PIN V15 [get_ports {o_test_result[12]}]
set_property PACKAGE_PIN T16 [get_ports {o_test_result[11]}]
set_property PACKAGE_PIN U14 [get_ports {o_test_result[10]}]
set_property PACKAGE_PIN T15 [get_ports {o_test_result[9]}]
set_property PACKAGE_PIN V16 [get_ports {o_test_result[8]}]
set_property PACKAGE_PIN U16 [get_ports {o_test_result[7]}]
set_property PACKAGE_PIN U17 [get_ports {o_test_result[6]}]
set_property PACKAGE_PIN V17 [get_ports {o_test_result[5]}]
set_property PACKAGE_PIN R18 [get_ports {o_test_result[4]}]
set_property PACKAGE_PIN N14 [get_ports {o_test_result[3]}]
set_property PACKAGE_PIN J13 [get_ports {o_test_result[2]}]
set_property PACKAGE_PIN K15 [get_ports {o_test_result[1]}]
set_property PACKAGE_PIN H17 [get_ports {o_test_result[0]}]

set_property PACKAGE_PIN V10 [get_ports {arguments[15]}]
set_property PACKAGE_PIN U11 [get_ports {arguments[14]}]
set_property PACKAGE_PIN U12 [get_ports {arguments[13]}]
set_property PACKAGE_PIN H6  [get_ports {arguments[12]}]
set_property PACKAGE_PIN T13 [get_ports {arguments[11]}]
set_property PACKAGE_PIN R16 [get_ports {arguments[10]}]
set_property PACKAGE_PIN U8  [get_ports {arguments[9]}]
set_property PACKAGE_PIN T8  [get_ports {arguments[8]}]
set_property PACKAGE_PIN R13 [get_ports {arguments[7]}]
set_property PACKAGE_PIN U18 [get_ports {arguments[6]}]
set_property PACKAGE_PIN T18 [get_ports {arguments[5]}]
set_property PACKAGE_PIN R17 [get_ports {arguments[4]}]
set_property PACKAGE_PIN R15 [get_ports {arguments[3]}]
set_property PACKAGE_PIN M13 [get_ports {arguments[2]}]
set_property PACKAGE_PIN L16 [get_ports {arguments[1]}]
set_property PACKAGE_PIN J15 [get_ports {arguments[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk_gl]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_sel[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_test_result[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {arguments[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {arguments[0]}]
